

fos_rest:
    body_converter:
        enabled: true
    view:
        view_response_listener: true
        formats: { json: true, xml: false, rss: false }
    serializer:
        serialize_null: true

    format_listener:
        rules:
            - { path: '^/', priorities: ['json'], fallback_format: 'json' }
